title:              Personal blog
tagline:            web development blog
description:        Tutorials and tips about web development, mostly Ruby and JS stuff.
url:                https://konstantinlebedev.com

author:
  name:             Konstantin Lebedev
  url:              https://twitter.com/koss_lebedev
  email:            koss.lebedev@gmail.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
